# Generated by Django 4.1.5 on 2023-01-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='teammember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('img', models.ImageField(upload_to='teamember/')),
            ],
        ),
    ]
