# Generated by Django 4.1.5 on 2023-01-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=6)),
                ('addresss', models.CharField(max_length=100)),
            ],
        ),
    ]
