# Generated by Django 4.1.6 on 2023-03-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_checkout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_catergories',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='user.sub_category'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='image',
            field=models.ImageField(upload_to='order/image'),
        ),
    ]
