# Generated by Django 4.1.6 on 2023-03-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_product_sub_catergories_alter_checkout_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_catgories',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='user.main_catgory'),
        ),
    ]
