# Generated by Django 4.2 on 2023-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='otp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
