# Generated by Django 4.2 on 2023-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_checkout_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
