# Generated by Django 4.2 on 2023-04-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_checkout_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
