# Generated by Django 4.2 on 2023-05-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_checkout_status_remove_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippername', models.CharField(max_length=30)),
                ('shipperemail', models.EmailField(max_length=254)),
                ('shipperpassword', models.IntegerField()),
                ('shipperaddress', models.TextField(max_length=255)),
                ('shipperphonenumber', models.IntegerField()),
                ('aadhar', models.FileField(upload_to='shipperaadhardoc/')),
                ('pancard', models.FileField(upload_to='shipperpancarddoc/')),
                ('drivinglience', models.FileField(upload_to='shipperdrivingliencedoc/')),
                ('shipperimage', models.ImageField(upload_to='shipper/image/')),
                ('dob', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='order_complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('product', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='completeorder/image')),
                ('quantity', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('total', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shipper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
